name: run-tests
on: [push]
jobs:
  run-contract-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Read node version from .nvmrc
        id: nvmrc
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: "${{ steps.nvmrc.outputs.NODE_VERSION }}"

      - name: Install dependencies
        run: npm install

      - run: npm test
