name: run-tests
on: [push]
jobs:
  run-contract-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Read node version from .nvmrc
        id: nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: "${{ steps.nvmrc.outputs.NODE_VERSION }}"

      - name: Install dependencies
        run: npm install

      - run: npm test
